### ISSUE TITLE
Clean asibot-main programs/modules

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/asibot-main#21]
There are a number of modules that should go elsewhere or become deprecated in favor of advances. This is not mandatory, but we have been working a lot elsewhere! I'm going to try to describe as honestly as possible the situation/past/present of each module.
- [x] testRaveBot -> Work in progress is to use [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins)  with separate model repos similar to [teo-openrave-models](https://github.com/roboticslab-uc3m/teo-openrave-models) to substitute testRaveBot and also teoSim of teo-main. For now only joint movements are implemented, but plugins for creating objects, publishing sensor data etc are on the way. GOOD TO KEEP :smile::minibus: (roboticslab-uc3m/openrave-yarp-plugins#26)
- [x] webInterface -> It's relatively pretty... GUIs are always nice... let's speak about this in person! (btw, in teo we're simply using the yarpmotorgui). GOOD TO KEEP :smile::minibus: hmi (roboticslab-uc3m/asibot-hmi#1)
- [x] pointAtObjectServer -> This was a PCL-based project, you sent a vector to it describing where you were pointing at (from some Windows Kinect software), and it did the classic RANSAC background extraction, Eucledean clustering to get objects, create meshes through Possion, and finally use VTK to get the intersection of the vector with one of the object meshes. GOOD TO KEEP :smile::truck: vision
- [x] robotDraw -> Was used for [the first xgnitive RIS paper](http://ieeexplore.ieee.org/document/6697181/?tp=&arnumber=6697181), should be moved to [xgnitive](https://github.com/roboticslab-uc3m/xgnitive) Don't remember actual implementation, and can only think of keeping it for historical reasons. MOVE. :truck: xgnitive
- [x] cartesianServer -> [teo-main BasicCartesianControl](https://github.com/roboticslab-uc3m/teo-main/tree/develop/libraries/TeoYarp/BasicCartesianControl) which also has a nice server wrapper + client pair in the same tree. My suggestion: ELIMINATE :skull_and_crossbones: (and move on to BasicCartesianControl, which is already a plugin).
- [x] colorSegmentor -> First one of the saga. 2D, had issues with blobs in OpenCV and ended up using a third-party library that's bulk imported. My suggestion: ELIMINATE. :skull_and_crossbones: 
- [x] kinectPxToReal ->Takes kinect X [px] and Y [px], joins with Z [m] to output X [m] Y [m] Z [m]. This is, it was a transition from 2D to 3D in a separate program. MOVE. :truck: vision
- [x] colorDepth -> Passes colorSegmentor to 3D. In fact, all colorDepth does is extract the depth of the corresponding pixel. Preserves issues with blobs in OpenCV and ended up using a third-party library that's bulk imported. My suggestion: ELIMINATE. :skull_and_crossbones: vision
- [x] visionSegmentor -> Improvement on colorDepth using travislib. Is 2D. Depends on [travislib](https://sourceforge.net/projects/travislibrary) (our wrapper of opencv). It feels like it could be a part of of somehow integrated within colorRegionDetection, but I really don't know how. GOOD TO KEEP :smile::truck: because it's 2D. vision
- [x] visionDepth ->Improvement on colorDepth using travislib. Is 3D.  Depends on [travislib](https://sourceforge.net/projects/travislibrary). In [colorRegionDetection](https://github.com/roboticslab-uc3m/teo-head/tree/develop/programs/colorRegionDetection) is an exact copy, just actually made a bulk copy of [travislib](https://sourceforge.net/projects/travislibrary) so you do not have to install it. However, we did do some improvements in documentation. My suggestion: ELIMINATE  :skull_and_crossbones: (and move on to colorRegionDetection which is more documented).
- [x] premultH -> Pre-multiplies an H, for an application such as premultiplying H_root_kinect to an incoming H_kinect_object to get H_root_object. Seems like overkill, but ROS's tf approach also feels like overkill. Another option is hard-coding an H0 into colorRegionDetection and similar. GOOD TO KEEP :smile::truck: kinematics
  - Alternatives include small library part of programs, or yarp port arbitration.
- [x] wiimoteServer -> Was nice, but could be better. For instance, I recall there was a hard-coded gui. A different solution with no dependencies on graphical environments, and better as a plugin, would be preferable. GOOD TO KEEP :smile::truck: yarp-devices
- [x] asibotTasks -> Sounded like a great idea, think I actually did some full trajectories like a man moving around a simulated environment and putting on some make-up, but can't think of a practical use for this. I actually recall this was when I was motivated with automated planning such as PDDL and wanted these to be atomic tasks. An idea is to migrate these demo-like behaviours to an interpreted language. GOOD TO KEEP :smile:
- [x] taskServer -> Most probably related to asibotTasks. I'd probably IMPROVE it, since it certainly isn't even a nice wrapper as in YARP devices. GOOD TO KEEP :smile::truck: demoServer

**Comment by jgvictores** [comment]
Updated info on testRaveBot: work at https://github.com/roboticslab-uc3m/openrave-yarp-plugins

**Comment by PeterBowman** [comment]
More to come: https://github.com/roboticslab-uc3m/asibot-main/issues/13#issuecomment-262739920.

**Comment by jgvictores** [comment]
Moved `pointAtObjectServer` at 0995af2158727327bb9b0753a825ef70a9cd0032, WIP on the current `import-pointAtObjectServer` branch at https://github.com/roboticslab-uc3m/vision.

**Comment by jgvictores** [comment]
Edit: Best to move `robotDraw` to [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins) rather than `xgnitive`.

**Comment by jgvictores** [comment]
Developing replacement for `premultH` on `transCoordsUsingJoints` branch of https://github.com/roboticslab-uc3m/kinematics-dynamics

**Comment by jgvictores** [comment]
In fact, `premultH` could be moved to https://github.com/roboticslab-uc3m/kinematics-dynamics as something like `transCoodsUsingH`.

**Comment by PeterBowman** [comment]
I've adapted the *wiimoteServer* application to work as a YARP plugin, done at roboticslab-uc3m/yarp-devices@b3d27fc. This is currently implemented as a `yarp::dev::IAnalogSensor` for simplicity/brevity, but should get its own interface and network wrapper sooner or later, with full control of all keys, sensors, rumble device and LEDs. Apart from that, I gave up on CWiiD and switched to the XWiimote library: [Install XWiimote](https://github.com/roboticslab-uc3m/installation-guides/blob/32f402df065c9363dd420fa6cb73efdee59f3ab1/install-xwiimote.md).

**Comment by PeterBowman** [comment]
> In fact, premultH could be moved to https://github.com/roboticslab-uc3m/kinematics-dynamics as something like transCoodsUsingH.

@jgvictores `transCoordsUsingJoints` was already written and merged in kinematics-dynamics at the time you posted this, did you mean that it should be renamed? I'm not sure what's left to do here, perhaps we can finally check that box.

**Comment by jgvictores** [comment]
The intention is to move and rename. `transCoordsH` and renamed `transCoordsUsingJoints` provide different functionalities.

**Comment by PeterBowman** [comment]
Oh, OK. To summarize:

* `transCoordsH`: formerly `premultH`, pre-multiplies a runtime-constant HT matrix (given via YARP configure option). Not done yet.
* `transCoordsUsingJoints`: same as above, but works with online HT (retrieves current joint angles from the robot control board and performs FK). Already done.

Please correct me if I'm wrong.

**Comment by jgvictores** [comment]
That's the objective, right!

**Comment by jgvictores** [comment]
visionSegmentor:
- Export: 2bba02f558809214f48b3333ed55844aa94e2d3e
- Import: https://github.com/roboticslab-uc3m/vision/commit/ec92007a8174f68eef4afd13d6d5cf78ea220346 and https://github.com/roboticslab-uc3m/vision/commit/2747559c170daa9ea0c9fa6f98f33f8fa19ed781

Will be renamed to colorRegionDetection2D, see https://github.com/roboticslab-uc3m/vision/issues/75

**Comment by PeterBowman** [comment]
premultH (re)moved at roboticslab-uc3m/kinematics-dynamics#137.

**Comment by jgvictores** [comment]
robotDraw moved to https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/d7c946bfa51b3bf012b5eab9962d427af3e58d8b/example/cpp/robotDraw at bf2b2cd55ccf5060f0acfa2fd42bbded415af47a

**Comment by jgvictores** [comment]
kinectPxToReal 1bc0569a5725ece3cc65e1540c7b3294817af2ff -> https://github.com/roboticslab-uc3m/vision/commit/c1529c4a1d282aff15fe395a6dd78524db67b985

**Comment by jgvictores** [comment]
Marked asibotTasks and taskServer, will be tracked on #40

**Comment by jgvictores** [comment]
mv matlab/visualServo out of repo done at 81f9a4075509629a639e4800b80e153fc1cf1be1.

Closing issue!

**Comment by jgvictores** [comment]
> mv matlab/visualServo out of repo done at 81f9a40.

Created https://github.com/roboticslab-uc3m/legacy-matlab-visual-servo for this legacy code, archived.
