### ISSUE TITLE
Clean asibot-main examples

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/asibot-main#38]
Clean asibot-main examples

**Comment by PeterBowman** [comment]
@jgvictores I forgot to tell you that there is ongoing work (#21, #28) on the `ycm-migration` branch. If you could, please work against it to keep track of the overall progress in migrating/cleaning files. I have just synced it `develop`.

**Comment by jgvictores** [comment]
No problem. I'm essentially just going to be deleting certain files from the `example` folder. Would you prefer if I do this directly on `ycm-migration` (if so, I guess on a branch and then merge --no-ff)?

**Comment by PeterBowman** [comment]
Oh, I didn't notice that I never actually touched the `example/` directory at all. No problem then if you choose to merge into `develop`, I'll keep up later with your changes on `ycm-migration`.

**Comment by jgvictores** [comment]
Done all but TaskLib at 71146f80b9c1bcd1675fb90ddeb7253fa528f6a9
