### ISSUE TITLE
Simulación Asibot en OpenRave.

### ISSUE THREAD

**Issue by serna92** [roboticslab-uc3m/asibot-main#43]
Buenas,

Quisiera saber si aún se puede instalar y utilizar cartesian server pues a la hora de hacer el ccmake .. ya no veo la opción cmake .. -DENABLE_cartesianServer. En caso negativo, ¿De qué manera podría realizar una simulación de Asibot con OpenRave?.

Saludos y gracias por adelantado.

**Comment by PeterBowman** [comment]
Hola. Hace poco reestructuramos el repositorio por completo, las funciones obsoletas como cartesianServer se encuentran ahora alojadas en otro lugar. Puedes utilizar la etiqueta `pre-ycm` para obtener un snapshot de asibot-main previo a dichos cambios: [link](https://github.com/roboticslab-uc3m/asibot-main/tree/pre-ycm), [enlace a descarga .zip](https://github.com/roboticslab-uc3m/asibot-main/archive/pre-ycm.zip). El método que funciona actualmente no se encuentra (aún) documentado, pero resumiendo mucho consistiría en compilar e instalar este mismo repositorio, buscar y lanzar el script [asibotSim](https://github.com/roboticslab-uc3m/asibot-configuration-files/blob/a56ec887641ef3a751fc8f587bcbcdd5df7842ed/scripts/bash/asibotSim).

**Comment by serna92** [comment]
Buenas, a la hora de hacer make obtengo el siguiente error de que no se encuentra el archivo Module.h. He probado a reinstalar Yarp pero no soluciona el problema, ¿qué puede estar fallando?

> [  6%] Building CXX object src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/TestRaveBot.cpp.o
In file included from /home/miguel/repos/asibot-main/src/libraries/TestRaveBotLib/TestRaveBot.cpp:3:0:
/home/miguel/repos/asibot-main/src/libraries/TestRaveBotLib/TestRaveBot.h:7:28: fatal error: yarp/os/Module.h: No existe el archivo o el directorio
compilation terminated.
src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/build.make:62: fallo en las instrucciones para el objetivo 'src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/TestRaveBot.cpp.o'
make[2]: *** [src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/TestRaveBot.cpp.o] Error 1
CMakeFiles/Makefile2:349: fallo en las instrucciones para el objetivo 'src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/all'
make[1]: *** [src/libraries/TestRaveBotLib/CMakeFiles/TestRaveBotLib.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
[  8%] Linking CXX static library ../../../lib/libTinyMath.a
[  8%] Built target TinyMath
[ 10%] Linking CXX static library ../../../lib/libCartesianClientLib.a
[ 10%] Built target CartesianClientLib
Makefile:129: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

>

**Comment by PeterBowman** [comment]
`Module.h` no existe desde YARP 2.3.72, puede que se dejase de instalar incluso antes. Puedes probar a sustituir `#include <yarp/os/Module.h>` por `#include <yarp/os/RFModule.h>` o intentarlo con una versión anterior de YARP. De todos modos, recordando un poco los pasos que dimos en #28, recomiendo migrar al nuevo sistema en el que el controlador monolítico se distribuye ahora entre varios repositorios con un propósito más claro (favoreciendo la generalización, reutilización de código, etc.). Por ejemplo, el módulo *WorldRpcResponder* sobre el que trabajaste se ha migrado a [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins) ([ref](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/tree/e27f1cfb74b7f98ca805ccdd1663c6fd9a14ed6e/libraries/OpenravePlugins/OpenraveYarpWorldRpcResponder)). Si haces un `make install` de lo último de asibot-main, deberías tener todo lo necesario para lanzar [este ejemplo de Python](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/blob/e27f1cfb74b7f98ca805ccdd1663c6fd9a14ed6e/examples/python/openraveYarpWorldRpcResponder.py).

**Comment by serna92** [comment]
Buenas, he conseguido cargar el entorno con el ejemplo en Python pero tengo dudas acerca de como enviar comandos RPC desde python una vez se ha cargado el módulo "openraveYarpWorldRpcResponder"

**Comment by jgvictores** [comment]
El comportamiento debe ser idéntico al antiguo. Para probar, puedes abrir una terminal:
```
yarp rpc /openraveYarpWorldRpcResponder/rpc:s
```
Y comandar todo lo que se indica vía `help`.

**Comment by PeterBowman** [comment]
Cerrando por inactividad.
